name: "Python Container Action Template @@@"
description: "Get started with Python Container actions @@@"
author: "Jacob Tomlinson @@@"
inputs:
  kubernetes_namespace:
    description: "@@@"
    required: true
  environment_name:
    description: "Input to use @@@"
    required: true
    #@@@ default: "world"
  github_secrets_json:
    description: "@@@"
    required: true
#@@@ outputs:
#@@@   myOutput:
#@@@     description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
  #@@@ TRY COMPOSITE? (SEE https://shipyard.build/blog/your-first-python-github-action/)
  # using: "composite"
  # steps:
  #   - run: ./main.py
  #     shell: bash