FROM python:3.9-slim AS builder
WORKDIR /app
RUN pip install --target=/app pyyaml
RUN apt update \
 && apt install -y curl \
 && rm -rf /var/lib/apt/lists/*
RUN curl -sSLO https://dl.k8s.io/release/v1.25.0/bin/linux/amd64/kubectl \
 && chmod a+x kubectl
RUN curl -sSLf https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.18.2/kubeseal-0.18.2-linux-amd64.tar.gz | tar xzf - \
 && chmod a+x kubeseal
ADD . /app

# A distroless container image with Python and some basics like SSL certificates
# https://github.com/GoogleContainerTools/distroless
#@@@ ADJUST IMAGE?
FROM gcr.io/distroless/python3-debian10
COPY --from=builder /app /app
WORKDIR /app
ENV PYTHONPATH /app
CMD ["/app/main.py"]
