name: Trigger ArgoCD webhook
on:
  push:
  workflow_dispatch:
jobs:
  webhook:
    runs-on: self-hosted
    uses: borsboom/seal-github-secrets-action/.github/workflows/argocd-webhook.yaml@main
    with:
      ARGOCD_WEBHOOK_URL: https://httpbin.org/anything
      RUNS_ON: self-hosted
