name: ArgoCD Deploy #@@@

on:
  workflow_dispatch:
    inputs:
      ARGOCD_APP:
        description: Application name #@@@
        type: string
        required: true
        default: app1
      ARGOCD_UPDATE_OVERLAYS:
        description: Update overlay names (space separated) #@@@
        type: string
        required: true
        default: dev azure-dev
      ARGOCD_PROMOTE_OVERLAYS:
        description: Promote overlay names (space separated) #@@@
        type: string
        required: true
        default: test aws-test
      IMAGE_TAG:
        description: Docker image tag #@@@
        type: string
        required: true
      BASE_COMMIT_REF:
        description: Base Kustomization commit reference #@@@
        type: string
        required: true

jobs:
  update:
    name: Deploy
    uses: borsboom/seal-github-secrets-action/.github/workflows/argocd_deploy.yaml@main #TODO: SPECIFY TAG
    secrets: inherit
    with:
      #@@@ NEED github.event.?
      ARGOCD_APP: ${{ github.event.inputs.ARGOCD_APP }}
      ARGOCD_UPDATE_OVERLAYS: ${{ github.event.inputs.ARGOCD_UPDATE_OVERLAYS }}
      ARGOCD_PROMOTE_OVERLAYS: ${{ github.event.inputs.ARGOCD_PROMOTE_OVERLAYS }}
      IMAGE_TAG: ${{ github.event.inputs.IMAGE_TAG }}
      BASE_COMMIT_REF: ${{ github.event.inputs.BASE_COMMIT_REF }}
