name: Main #@@@

on:
  push:
    #TODO: REMOVE ON PUSH
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  dev:
    uses: ./.github/workflows/update_sealed_secrets.yaml
    secrets: inherit
    with:
      environment: dev
      kubernetes_namespace: myns

  test:
    needs: dev
    uses: ./.github/workflows/update_sealed_secrets.yaml
    secrets: inherit
    with:
      environment: test
      kubernetes_namespace: myns
