name: Main #@@@

on:
  push:
    #TODO: REMOVE ON PUSH
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  #@@@ ADD A COMMON WORKFLOW FOR ALL NON-SHARED ENVIRONMENTS
  dev:
    uses: borsboom/github-sealed-secrets-action@main #@@@ SPECIFY TAG
    secrets: inherit
    with:
      environment: dev
      kubernetes_namespace: myns

  test:
    needs: dev
    uses: borsboom/github-sealed-secrets-action@main #@@@ SPECIFY TAG
    secrets: inherit
    with:
      environment: test
      kubernetes_namespace: myns
