name: Main #@@@

on:
  push:
    #TODO: REMOVE ON PUSH
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  #@@@ ADD A COMMON WORKFLOW FOR ALL NON-SHARED ENVIRONMENTS
  #@@@ JOB NAME?
  all:
    uses: borsboom/github-sealed-secrets-action/.github/workflows/update_sealed_secrets_all_environments.yaml@main #@@@ SPECIFY TAG
    secrets: inherit
    with:
      kubernetes_namespace: myns
