name: Update secrets
on:
  workflow_dispatch:
jobs:

  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Update secrets
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  test:
    needs: [dev]
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: Update secrets
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
