name: Update Kubernetes sealed secrets from Github secrets

on:
  workflow_dispatch:
    inputs:
      dev:
        description: "Update secrets in Dev environment"
        type: boolean
        default: true
      test:
        description: "Update secrets in Test environment"
        type: boolean
        default: true
      staging:
        description: "Update secrets in Staging environment"
        type: boolean
        default: true
      prod:
        description: "Update secrets in Production environment"
        type: boolean
        default: true
      shared:
        description: "Update secrets in Shared Services environment"
        type: boolean
        default: true

jobs:
  all_environments:
    name: All environments
    uses: borsboom/seal-github-secrets-action/.github/workflows/update_sealed_secrets_all_environments.yaml@main #TODO: SPECIFY TAG
    secrets: inherit
    with:
      kubernetes_namespace: myns
