name: Update Kubernetes sealed secrets from Github secrets

on:
  workflow_dispatch:

jobs:
  all_environments:
    name: All environments
    uses: borsboom/seal-github-secrets-action/.github/workflows/update_sealed_secrets_all_environments.yaml@main #TODO: SPECIFY TAG
    secrets: inherit
    with:
      kubernetes_namespace: myns
