name: Update sealed secrets from Github secrets #@@@

on:
  workflow_dispatch:
  #TODO: REMOVE ON PUSH
  push:
    branches: [ "main" ]

jobs:
  #@@@ JOB NAME?
  all_environments:
    name: All environments
    uses: borsboom/github-sealed-secrets-action/.github/workflows/update_sealed_secrets_all_environments.yaml@main #@@@ SPECIFY TAG
    secrets: inherit
    with:
      kubernetes_namespace: myns
