name: Update Kubernetes sealed secrets from Github secrets

on:
  workflow_dispatch:
    inputs:
      dev:
        description: "Development environment"
        type: boolean
        default: true
      test:
        description: "Test environment"
        type: boolean
        default: false #@@@ true
      staging:
        description: "Staging environment"
        type: boolean
        default: false #@@@ true
      prod:
        description: "Production environment"
        type: boolean
        default: false #@@@ true
      shared:
        description: "Shared Services environment"
        type: boolean
        default: false #@@@ true

jobs:
  update:
    name: Update
    uses: borsboom/seal-github-secrets-action/.github/workflows/update_sealed_secrets_in_multiple_environments.yaml@main #TODO: SPECIFY TAG
    secrets: inherit
    with:
      kubernetes_namespace: myns
      dev: ${{ inputs.dev }}
      test: ${{ inputs.test }}
      staging: ${{ inputs.staging }}
      prod: ${{ inputs.prod }}
      shared: ${{ inputs.shared }}
