name: Update Kubernetes sealed secrets from Github secrets

on:
  workflow_dispatch:
    inputs:
      dev:
        description: "dev environment"
        type: boolean
        default: true
      test:
        description: "test environment"
        type: boolean
        default: true
      staging:
        description: "staging environment"
        type: boolean
        default: true
      prod:
        description: "prod environment"
        type: boolean
        default: true
      shared:
        description: "shared environment"
        type: boolean
        default: true

jobs:
  update:
    name: Update
    uses: borsboom/seal-github-secrets-action/.github/workflows/update_sealed_secrets_in_multiple_environments.yaml@main #TODO: SPECIFY TAG
    secrets: inherit
    with:
      kubernetes_namespace: dev-emanuel-borsboom
      dev: ${{ inputs.dev }}
      test: ${{ inputs.test }}
      staging: ${{ inputs.staging }}
      prod: ${{ inputs.prod }}
      shared: ${{ inputs.shared }}
